export const BOOK_LIST_FETCH_START = 'BOOK_LIST_FETCH_START';
export const BOOK_LIST_FETCH_IN_PROGRESS = 'BOOK_LIST_FETCH_IN_PROGRESS';
export const BOOK_LIST_FETCH_SUCCESS = 'BOOK_LIST_FETCH_SUCCESS';
export const BOOK_LIST_FETCH_ERROR = 'BOOK_LIST_FETCH_ERROR';
