export const BOOK_ITEM_FETCH_START = "BOOK_ITEM_FETCH_START";
export const BOOK_ITEM_FETCH_IN_PROGRESS = "BOOK_ITEM_FETCH_IN_PROGRESS";
export const BOOK_ITEM_FETCH_SUCCESS = "BOOK_ITEM_FETCH_SUCCESS";
export const BOOK_ITEM_FETCH_ERROR = "BOOK_ITEM_FETCH_ERROR";
