export const STATISTICS_FETCH_START = 'STATISTICS_FETCH_START';
export const STATISTICS_FETCH_IN_PROGRESS = 'STATISTICS_FETCH_IN_PROGRESS';
export const STATISTICS_FETCH_SUCCESS = 'STATISTICS_FETCH_SUCCESS';
export const STATISTICS_FETCH_ERROR = 'STATISTICS_FETCH_ERROR';
